FROM node:20

# Set the working directory
WORKDIR /app/backend/product-service

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install 


# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3002

# Command to run the application
CMD ["npm", "run", "dev"]