# Use an official, smaller Node.js base image
FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy app files
COPY . .

# Optional: Run tests or build here if needed
# RUN npm run build

# Use a smaller runtime image for final container
FROM node:18-alpine

WORKDIR /app

# Only copy the built app and node_modules from builder
COPY --from=builder /app /app

EXPOSE 3001

CMD ["node", "server.js"]
